---
name: Build container image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - .github/workflows/build-container-image.yml
      - Containerfile
      - files/**
      - osism/**
      - requirements.ansible.txt
      - requirements.txt
      - requirements.yml
      - scripts/**
      - setup.cfg
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/build-container-image.yml
      - Containerfile
      - files/**
      - osism/**
      - requirements.ansible.txt
      - requirements.txt
      - requirements.yml
      - scripts/**
      - setup.cfg

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - run: scripts/build.sh
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REPOSITORY: osism/osism
      - run: |
          scripts/push.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          REPOSITORY: osism/osism
        if: |
          github.repository == 'osism/python-osism' &&
          github.ref == 'refs/heads/main'
